version: "3.9"

services:
  app:
    build: .
    container_name: chat-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=5000
    ports:
      - "80:5000"
    # Uncomment if you want to control memory/CPU limits
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.50'
    #       memory: 512M
