-- سكربت إنشاء جدول users كما هو معرف في السكيمة البرمجية
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password TEXT,
    user_type TEXT NOT NULL DEFAULT 'guest',
    profile_image TEXT,
    profile_banner TEXT,
    status TEXT,
    gender TEXT,
    age INTEGER,
    country TEXT,
    relation TEXT,
    bio TEXT,
    is_online BOOLEAN DEFAULT FALSE,
    is_hidden BOOLEAN DEFAULT FALSE,
    last_seen TIMESTAMP,
    join_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_muted BOOLEAN DEFAULT FALSE,
    mute_expiry TIMESTAMP,
    is_banned BOOLEAN DEFAULT FALSE,
    ban_expiry TIMESTAMP,
    is_blocked BOOLEAN DEFAULT FALSE,
    ip_address VARCHAR(45),
    device_id VARCHAR(100),
    ignored_users TEXT[],
    username_color TEXT DEFAULT '#FFFFFF',
    user_theme TEXT DEFAULT 'default',
    profile_background_color TEXT DEFAULT '#3c0d0d'
);