name: Comment on PR when branch is updated

on:
  push:
    branches-ignore:
      - main
      - stable-main
      - 'backup/**'
      - 'revert-*'
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create or update PR comment for this push
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const ref = context.ref.replace('refs/heads/','');
            let pr;
            if (context.eventName === 'pull_request') {
              pr = context.payload.pull_request;
            } else {
              const { data } = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head: `${context.repo.owner}:${ref}`,
                state: 'open',
              });
              pr = data[0];
            }
            if (!pr) {
              core.info(`No open PR for branch ${ref}. Skipping comment.`);
              return;
            }
            const sha = context.sha.substring(0,7);
            const headCommit = (context.payload || {}).head_commit || {};
            const message = headCommit.message || '';
            const actor = context.actor || 'unknown';
            const body = [
              `🔄 Branch \`${ref}\` was updated`,
              `- Commit: \`${sha}\``,
              `- Actor: @${actor}`,
              message ? `- Message: ${message}` : null,
            ].filter(Boolean).join('\n');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body,
            });
